### PR TITLE
Support sweetaler2

### PR DESCRIPTION
**Pull request by kvaillant**
Hi, is it possible to merge this to get support for sweet alert 2 please ?
http://limonte.github.io/sweetalert2/

### CODE REVIEW

**Comment by tushar-borole** [comment]
@kvaillant  Changing the core library version will create a problem, may be a scope for ng-sweet-alert2 :+1:

**Comment by limonte** [comment]
Hi @tushariscoolster, I'm the author of sweetalert2.

Original plugin is currently inactive and unsupported. Sweetalert2 is far ahead and it has a ton of additional cool features, as inputs types, modals chaining etc.

Swal2 also has several active contributors and most probably it won't be dead as original swal.

For ng-sweet-alert transition from swal to swal2 should be pretty easy, I'm available for any help.

The only one big difference is using Promises instead of callbacks (yeah, it's 2016 now :smile:): https://github.com/limonte/sweetalert2/releases/tag/v1.0.0

**Comment by tushar-borole** [comment]
@limonte  am glad you replied,
Currently am busy with other project,
One thing we can do is depending on which library is loaded, we can can carry out the code execution
You can make pull request to this repo if you have time to do it
or else i gotto take out some time may be next month

Thank you

**Comment by kvaillant** [comment]
@limonte I released this repo https://github.com/kvaillant/ng-sweet-alert-2. You are a collabartor.
@tushariscoolster I can add you too if you wish

**Comment by tushar-borole** [comment]
@kvaillant  Thank you

**Pull request closed without merging**
